### ISSUE TITLE
add snapshot support

### ISSUE THREAD

**Issue by cztomsik** [volument/baretest#1]
Hey, I really love the project but snapshot support would be a huge plus, or maybe at least provide something 3rd party?

And specifically, one of the greatest things about jest is `toMatchInlineSnapshot`

**Comment by tipiirai** [comment]
Thanks! Snapshotting is outside the scope of Baretest and should indeed be handled by a 3rd party. Is there one? Would make a great example on the docs.

**Comment by cztomsik** [comment]
I don't know about any

but `toMatchInlineSnapshot ` would be hard to handle by 3rd party module because it needs to know path of the currently executed script so that it can make changes to that file.

also, passing `--update` would need to happen through env variables I guess or I don't know otherwise, baretest doesn't include any cli

**Comment by tipiirai** [comment]
Gotcha. Then I suppose Jest is your best pick if snapshotting is a requirement. At least for now.

**Comment by bfulop** [comment]
Hi, 

Thanks for creating this library it may just be what I was looking for! (Putting _interactive dev_ into TDD)

Shouldn't the examples use `assert.equal` instead of `assert.equals`?

**Comment by tipiirai** [comment]
Thanks, @bfulop! Good to hear. A friendly [PR](https://github.com/volument/baretest/pull/5) from @fromflux fixed the example. 

> Putting interactive dev into TDD

This is sounding good and useful. Can you shed some more light on that? I could possibly write more about that on the docs.

**Comment by bfulop** [comment]
Hiy @tipiirai, sorry I just realised that I posted in the wrong issue (was meant to add it to #3) !

Basically what I meant by interactivity was that Baretest is so fast that it starts to feel interactive. I hit save and immediately see the results. (I'm using nodemon to restart the tests, if you have other suggestions I'm interested!)
Of course there's more to interactive programming, e.g. the current state of your program is preserved while you are making changes to your code, and the changes are applied as patches to your running application.

I just started using Baretest on a side-project and I really enjoy working with it. Most testing libraries want to help you too much, and define their own way of running your code (especially when it comes to async), and in the end you spend a lot of time figuring out how they want you to write your tests.

With Baretest, you are in control, you just write normal JavaScript, and you know exactly in which order your code will be executed.

And I also agree with you that most of my tests are very simple (`equal`) assertions!

I may try to add testdouble.js for stubbing out my modules - I think it should integrate well with Baretest.

**Comment by tipiirai** [comment]
So happy to hear about your positive experiences! Seems you have perfectly understood the use case for Baretest. 

I personally start node from scratch every time I run a test in Sublime, but your idea of using nodemon sounds viable — if I can just get the results in Sublime buffer easily and there is a good way to make it work across multiple repositories. (I have many repos imported to the same Sublime project)

 I've thought of using a file watcher, but maybe nodemon is better? 

Thank you for clarifying the characteristics of "interactive TDD"!
