### ISSUE TITLE
I dont get what should be in a distributed test

### ISSUE THREAD

**Issue by aldomendez** [volument/baretest#12]
Hi, I just get how to make your single test file example to work. Thanks for that,

What I don't get is what should be in the files __required__ that make [this example](https://volument.com/baretest#organizing-multiple-tests) to work.

Can you please share a sample file so I can replicate this pattern:

```js
const test = require('baretest')('My app'),
  assert = require('assert'),
  app = require('my-app')

require('./test/users')(test, assert, app)
require('./test/teams')(test, assert, app)
require('./test/sharing')(test, assert, app)
require('./test/commenting')(test, assert, app)
require('./test/billing')(test, assert, app)
// require('./test/mailer')(test, assert, app)
// require('./test/management')(test, assert, app)

!(async function() {
  await test.run()
})()
```

Thank you.

**Comment by lusbuab** [comment]
Hi @aldomendez, this is something I was also wondering about. According to the source code of [`baretest`](https://github.com/volument/baretest/blob/5307f8f304e62f320ce138bfef3a0d5ea9915a24/baretest.js) it currently is not possible to get the same exact nice output as in the screenshot on the  [baretest website](https://volument.com/baretest).

I ended up with this:

```js
// baretest calls console.info at the end of the suite. 
// this adds ugly new lines between the output of multiple suits
// let's redefine console.info to get rid of those extra line breaks
console.info = () => {};

async function runTests() {
  await require("./test/users").run();
  await require("./test/teams").run();
  await require("./test/sharing").run();
  await require("./test/commenting").run();
  await require("./test/billing").run();
}

runTests();
```

Then each of the test files exports the test suite like this:

```js
const test = module.exports = require("baretest")("Users");
const assert = require("assert");

test("...", function () { /* ... */ })
```

**Comment by aldomendez** [comment]
Thank you dude,

I end up with this working code:

```js
import {test as distributionsTest} from './distributions/test.js'
import {test as eventManagerTest} from './eventManager/test.js'
import {test as heapTest} from './heap/test.js'

console.info = () => {};

async function runTests() {
  await distributionsTest.run();
  await eventManagerTest.run();
  await heapTest.run();
}

runTests();
```

**Comment by tipiirai** [comment]
Sorry for not getting back to this one. The above is exactly the idea. It's up to the user to organize the files and make the "suite". Thank you @aldomendez for giving the details!

This project has been a bit less active on my side than I planned when releasing. This will change. I think the JS ecosystem needs a minimal testing tool. Jest and likes have their places on large/complex projects, but the default should be way more trivial. Not saying Baretest is the one, could be anything.
