### ISSUE TITLE
Examples in README and documentation use wrong API

### ISSUE THREAD

**Issue by marcelbeumer** [volument/baretest#3]
First of all thanks for baretest! I'm a long time mocha user, super frustrated with the perf of jest and really happy to see this minimal test runner coming by!

I found two errors in the documentation. 

Example #1 (both README and docs):

```
const test = require('baretest'),
  assert = require('assert'),
  app = require('my-app')

test('add user', async function() {
...
```

The example should call `require('basetest')('Test descr')` before adding tests.

Example #2 (docs):

```
const assert = require('assert'),
  test = require('baretest'),
  app = require('my-app')

require('./test/users')(test, assert, app)
require('./test/teams')(test, assert, app)
require('./test/sharing')(test, assert, app)
require('./test/commenting')(test, assert, app)
require('./test/billing')(test, assert, app)
// require('./test/mailer')(test, assert, app)
// require('./test/management')(test, assert, app)

!(async function() {
  await test.run()
})()
```

There is no toplevel `test.run()`! Actually, it would be convenient to have it, but then you'd have to keep state in your module, and we'd need a `test.reset()` or so too. I *just now* used baretest but by wrapping the mocha describe/it-API, so could keep track of different suites over different files myself, but how would you otherwise do it without the toplevel `.run`?

**Comment by tipiirai** [comment]
Thank you Marcel! I just added the `require('basetest')('Test descr')` to the docs. Good catch. 

On the second example there is just one `run` call to run all the tests. You can also do following:

```
const baretest = require('baretest')

const suite1 = baretest('Users')

suite1.test('add user', fn)
suite1.test('update user', fn)
...

const suite2 = baretest('Users')

suite2.test('add user', fn)
suite2.test('update user', fn)
...

test.run()
```

Does that work for you?

**Comment by marcelbeumer** [comment]
@tipiirai I know, yes, but it would only work if you'd add `test.run()` in each test file. And the example is not correct, because it calls `test.run` toplevel

**Comment by tipiirai** [comment]
Hmm.. the `test` variable is defined with the `require('basetest')('Test descr')` call, which has the `run` method.

**Comment by tipiirai** [comment]
The example on the README is now also fixed. Thanks!

**Comment by marcelbeumer** [comment]
Ah yes I see with `const test = require('baretest')('My app'),` it works. You now can't have new "suites" in any of these kind of files `require('./test/users')(test, assert, app)` but understand that's by design.
